bump Zephyr to newest pre-zcbor revision
zcbor is deprecating tinycbor library in newest Zephyr revisions. Bump
Zephyr to revision that predates first zcbor use so there is time for
converting internal tinycbor usage to zcbor.

Update nrf52840dk_nrf52840 DT overlays to use pinctrl instead of
proprietary '-pin' properties in order to solve following build error:

  /zephyr/soc/arm/nordic_nrf/common/./soc_nrf_common.h:229:2: error: \
    static assertion failed: "/soc/uart@40028000 has legacy *-pin \
    properties defined although PINCTRL is enabled"
    229 |  BUILD_ASSERT(!IS_ENABLED(CONFIG_PINCTRL) ||   \
        |  ^~~~~~~~~~~~
  /zephyr/drivers/serial/uart_nrfx_uarte.c:2053:2: note: in expansion \
    of macro 'NRF_DT_CHECK_PIN_ASSIGNMENTS'
   2053 |  NRF_DT_CHECK_PIN_ASSIGNMENTS(UARTE(idx), 1,          \
        |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /zephyr/drivers/serial/uart_nrfx_uarte.c:2147:1: note: in expansion \
    of macro 'UART_NRF_UARTE_DEVICE'
   2147 | UART_NRF_UARTE_DEVICE(1);
        | ^~~~~~~~~~~~~~~~~~~~~

Semi-automated code change with manually generated patch and following
shell loop:

  for f in `find -name nrf52840dk_nrf52840.overlay`; do
      echo Patching $f
      patch -p1 $f < /tmp/p.patch
  done

Replace deprecated UTIL_LISTIFY() with LISTIFY() macro in lightdb_led
sample.

Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>