bump Zephyr and NCS to tip of main
Update nrf52840dk_nrf52840 DT overlays to use pinctrl instead of
proprietary '-pin' properties in order to solve following build error:

  /zephyr/soc/arm/nordic_nrf/common/./soc_nrf_common.h:229:2: error: \
    static assertion failed: "/soc/uart@40028000 has legacy *-pin \
    properties defined although PINCTRL is enabled"
    229 |  BUILD_ASSERT(!IS_ENABLED(CONFIG_PINCTRL) ||   \
        |  ^~~~~~~~~~~~
  /zephyr/drivers/serial/uart_nrfx_uarte.c:2053:2: note: in expansion \
    of macro 'NRF_DT_CHECK_PIN_ASSIGNMENTS'
   2053 |  NRF_DT_CHECK_PIN_ASSIGNMENTS(UARTE(idx), 1,          \
        |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
  /zephyr/drivers/serial/uart_nrfx_uarte.c:2147:1: note: in expansion \
    of macro 'UART_NRF_UARTE_DEVICE'
   2147 | UART_NRF_UARTE_DEVICE(1);
        | ^~~~~~~~~~~~~~~~~~~~~

Semi-automated code change with manually generated patch and following
shell loop:

  for f in `find -name nrf52840dk_nrf52840.overlay`; do
      echo Patching $f
      patch -p1 $f < /tmp/p.patch
  done

After commit "lib: nrf_modem: don't enforce socket priority over native
TLS" was merged into 'main' branch it is possible to configure priority
of Zephyr TLS implementation to be higher than offloaded nRF9160 TLS.
This makes it possible to select Zephyr TLS (mbedTLS) implementation at
build time, which was not possible from NCS 1.8.0.

Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>