gitlab-ci: call 'west forall ...' only when 'west update ...' failed
Suppress following error:

  $ west forall -c 'git clean -ffdx && git reset --hard'

  FATAL ERROR: failed manifest import in nrf (nrf)
    Missing file: "west.yml" from revision "v1.7.1"
    Hint: for this to work:
            - nrf must be cloned
            - its manifest-rev ref must point to a commit with the \
              missing file
          To fix, run:
            west update

which is triggered some repositories repositories ('nrf' in above case)
are not cloned yet with 'west update' command. Execute 'west update'
first and do git repository cleanup followed by second update attempt
only when first update failed (potentially because of cached local
changed to the repositories).

Signed-off-by: Marcin Niestroj <m.niestroj@emb.dev>